# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hub.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hub.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\thub.proto\x12\x03hub\"\xcc\x01\n\nEventChunk\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12/\n\x08metadata\x18\x06 \x03(\x0b\x32\x1d.hub.EventChunk.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xb6\x01\n\tFileChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\x12\n\ntotal_size\x18\x03 \x01(\x03\x12\x14\n\x0c\x63hunk_number\x18\x04 \x01(\x05\x12.\n\x08metadata\x18\x05 \x03(\x0b\x32\x1c.hub.FileChunk.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x7f\n\x0eUploadResponse\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x19\n\x11original_filename\x18\x02 \x01(\t\x12\x0c\n\x04size\x18\x03 \x01(\x03\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x0f\n\x07success\x18\x05 \x01(\x08\x12\x0f\n\x07message\x18\x06 \x01(\t\"\"\n\x0f\x44ownloadRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\" \n\rDeleteRequest\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2B\n\nDataStream\x12\x34\n\x0cStreamEvents\x12\x0f.hub.EventChunk\x1a\x0f.hub.EventChunk(\x01\x30\x01\x32\xa5\x01\n\x0b\x46ileService\x12/\n\x06Upload\x12\x0e.hub.FileChunk\x1a\x13.hub.UploadResponse(\x01\x12\x32\n\x08\x44ownload\x12\x14.hub.DownloadRequest\x1a\x0e.hub.FileChunk0\x01\x12\x31\n\x06\x44\x65lete\x12\x12.hub.DeleteRequest\x1a\x13.hub.DeleteResponseBQ\n\x0f\x63om.deepapp.hubB\tHubProtosP\x01Z1github.com/k23doanngocthanh/go_grpc_hub/proto/hubb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.deepapp.hubB\tHubProtosP\001Z1github.com/k23doanngocthanh/go_grpc_hub/proto/hub'
  _globals['_EVENTCHUNK_METADATAENTRY']._loaded_options = None
  _globals['_EVENTCHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_FILECHUNK_METADATAENTRY']._loaded_options = None
  _globals['_FILECHUNK_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EVENTCHUNK']._serialized_start=19
  _globals['_EVENTCHUNK']._serialized_end=223
  _globals['_EVENTCHUNK_METADATAENTRY']._serialized_start=176
  _globals['_EVENTCHUNK_METADATAENTRY']._serialized_end=223
  _globals['_FILECHUNK']._serialized_start=226
  _globals['_FILECHUNK']._serialized_end=408
  _globals['_FILECHUNK_METADATAENTRY']._serialized_start=176
  _globals['_FILECHUNK_METADATAENTRY']._serialized_end=223
  _globals['_UPLOADRESPONSE']._serialized_start=410
  _globals['_UPLOADRESPONSE']._serialized_end=537
  _globals['_DOWNLOADREQUEST']._serialized_start=539
  _globals['_DOWNLOADREQUEST']._serialized_end=573
  _globals['_DELETEREQUEST']._serialized_start=575
  _globals['_DELETEREQUEST']._serialized_end=607
  _globals['_DELETERESPONSE']._serialized_start=609
  _globals['_DELETERESPONSE']._serialized_end=659
  _globals['_DATASTREAM']._serialized_start=661
  _globals['_DATASTREAM']._serialized_end=727
  _globals['_FILESERVICE']._serialized_start=730
  _globals['_FILESERVICE']._serialized_end=895
# @@protoc_insertion_point(module_scope)
